<x-layouts.app :title="$project->name">
    <x-page-header :title="$project->name" :description="$project->description" :back="route('projects.index')">
        <x-slot:meta><div class="mt-3 flex flex-wrap items-center gap-3"><x-project-status-badge :status="$project->status" /><x-health-badge :health="$project->health" /><span class="text-sm text-slate-500">Owner: {{ $project->owner?->name }}</span></div></x-slot:meta>
        <x-slot:actions>@can('update', $project)<a href="{{ route('projects.edit', $project) }}" class="btn-secondary"><x-icon name="pencil" class="h-4 w-4" /> Edit</a>@endcan @can('delete', $project)<form method="POST" action="{{ route('projects.destroy', $project) }}" onsubmit="return confirm('Delete this project and its tasks?')">@csrf @method('DELETE')<button class="btn-danger" type="submit"><x-icon name="trash" class="h-4 w-4" /> Delete</button></form>@endcan</x-slot:actions>
    </x-page-header>
    <div class="grid gap-5 lg:grid-cols-[minmax(0,1fr)_20rem]">
        <section class="space-y-5"><div class="card"><div class="card-header flex items-center justify-between"><h2 class="card-title">Tasks</h2><a class="btn-primary btn-sm" href="{{ route('tasks.create', ['project_id' => $project->id]) }}"><x-icon name="plus" class="h-4 w-4" /> Add task</a></div><div class="divide-y divide-slate-100">@forelse($project->tasks as $task)<x-task-row :task="$task" :show-project="false" />@empty<div class="card-body"><x-empty-state icon="tasks" title="No tasks yet" description="Add the first task to this project." /></div>@endforelse</div></div></section>
        <aside class="space-y-5"><div class="card"><div class="card-header"><h2 class="card-title">Progress</h2></div><div class="card-body"><x-progress-bar :value="$project->progress" size="lg" :show-label="true" /><p class="mt-3 text-sm text-slate-500">{{ $project->tasks_count ?? $project->tasks->count() }} top-level tasks</p></div></div><div class="card"><div class="card-header"><h2 class="card-title">Members</h2></div><div class="card-body space-y-3">@foreach($project->members as $member)<div class="flex items-center gap-2"><x-avatar :user="$member" size="sm" /><span class="min-w-0 flex-1 truncate text-sm">{{ $member->name }}</span><span class="text-xs text-slate-500">{{ ucfirst($member->pivot->role) }}</span></div>@endforeach @can('manageMembers', $project)<a class="btn-secondary btn-sm mt-2 w-full" href="#members">Manage members</a>@endcan</div></div></aside>
    </div>
</x-layouts.app>
