import path from 'node:path';
import { migrate } from 'drizzle-orm/node-postgres/migrator';
import { db } from '.';

/** Apply pending SQL migrations from ./drizzle (generated by `npm run db:generate`). */
export async function runMigrations(): Promise<void> {
    await migrate(db(), { migrationsFolder: path.join(process.cwd(), 'drizzle') });
}
